"""Base class for parsing summaries generated by click.
"""
from __future__ import division
from copy import deepcopy
from collections import Counter
from enum import Enum, unique
import json

__author__ = """\n""".join(['Vivek Shrivastava (vivek@obiai.tech)'])

class ParseWirelessSummary(object):
    """Parses wireless summary generated by click
    """
    def __init__(self, wireless_summary=None, 

class ParseNodeSummary(object):

class ParseTCPSummary(object):
    """
    Base class for a Flow.

    Flow {
        Vector edgeList[MAX_HOPS] // An ordered list of edges
        FlowType flowType[MAX_PROTOCOL_LAYERS] // A list of protocols like HTTP/TCP/IP
        Int Port
        FlowMetrics flowMetrics  // Captures network metrics for this flow.
    } 

    """
    def __init__(self, edge_list=[], flow_type=FlowType.UNKNOWN, port=0, **metrics)
        self.edge_list = edge_list
        self.flow_type = flow_type
        self.port = port
        self.flow_metrics = Counter()
        self.flow_metrics.update(metrics)

    def update_metrics(self, metrics):
        self.flow_metrics.update(metrics)
